# -*- Mode: Python -*-

Import('kernel_env')

kernel_env.Program(target = 'x86.lo', source = [
Glob('*.c'),
kernel_env['BSP']+'/' + kernel_env['BSP'] + '.lo'])

SConscript(kernel_env['BSP']+'/SConscript')

# EOF
