#******************************************************************
#
# Institute for System Programming of the Russian Academy of Sciences
# Copyright (C) 2016 ISPRAS
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, Version 3.
#
# This program is distributed in the hope # that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU General Public License version 3 for more details.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

import os

Import('env')

part_dir = Dir('.').abspath
part_build_dir = os.path.join(part_dir, 'build', env['BSP'], '')
src_dir = os.path.join(part_dir, 'src', '')

part_xml = 'config.xml'
Export('part_xml')

part_elf = SConscript(env['POK_PATH']+'/misc/SConscript_partition',
    exports = ['part_dir', 'part_build_dir', 'src_dir'])

Return('part_elf')
