/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <core/setjmp.h>
#include <unity/unity.h>
#include <unity/cmock.h>
#include <mocks/MockARINC_SENDER_gen.h>

static const char* CMockString_ARINC_SENDER_call_portA_flush = "ARINC_SENDER_call_portA_flush";
static const char* CMockString_ARINC_SENDER_call_portA_send = "ARINC_SENDER_call_portA_send";
static const char* CMockString_cmock_arg1 = "cmock_arg1";
static const char* CMockString_cmock_arg2 = "cmock_arg2";
static const char* CMockString_cmock_arg3 = "cmock_arg3";
static const char* CMockString_cmock_arg4 = "cmock_arg4";

typedef struct _CMOCK_ARINC_SENDER_call_portA_send_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  ret_t ReturnVal;
  ARINC_SENDER* Expected_cmock_arg1;
  char* Expected_cmock_arg2;
  size_t Expected_cmock_arg3;
  size_t Expected_cmock_arg4;

} CMOCK_ARINC_SENDER_call_portA_send_CALL_INSTANCE;

typedef struct _CMOCK_ARINC_SENDER_call_portA_flush_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  ret_t ReturnVal;
  ARINC_SENDER* Expected_cmock_arg1;

} CMOCK_ARINC_SENDER_call_portA_flush_CALL_INSTANCE;

static struct MockARINC_SENDER_genInstance
{
  CMOCK_MEM_INDEX_TYPE ARINC_SENDER_call_portA_send_CallInstance;
  CMOCK_MEM_INDEX_TYPE ARINC_SENDER_call_portA_flush_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void MockARINC_SENDER_gen_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_ARINC_SENDER_call_portA_send);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.ARINC_SENDER_call_portA_send_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_ARINC_SENDER_call_portA_flush);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.ARINC_SENDER_call_portA_flush_CallInstance, cmock_line, CMockStringCalledLess);
}

void MockARINC_SENDER_gen_Init(void)
{
  MockARINC_SENDER_gen_Destroy();
}

void MockARINC_SENDER_gen_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

ret_t ARINC_SENDER_call_portA_send(ARINC_SENDER* cmock_arg1, char* cmock_arg2, size_t cmock_arg3, size_t cmock_arg4)
{
if (!ARINC_SENDER_call_portA_send_UseMock)
{
  return _ARINC_SENDER_call_portA_send_impl(cmock_arg1, cmock_arg2, cmock_arg3, cmock_arg4);
}
else
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_ARINC_SENDER_call_portA_send_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_ARINC_SENDER_call_portA_send);
  cmock_call_instance = (CMOCK_ARINC_SENDER_call_portA_send_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.ARINC_SENDER_call_portA_send_CallInstance);
  Mock.ARINC_SENDER_call_portA_send_CallInstance = CMock_Guts_MemNext(Mock.ARINC_SENDER_call_portA_send_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_ARINC_SENDER_call_portA_send,CMockString_cmock_arg1);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_cmock_arg1), (void*)(cmock_arg1), sizeof(ARINC_SENDER), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_ARINC_SENDER_call_portA_send,CMockString_cmock_arg2);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_cmock_arg2, cmock_arg2, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_ARINC_SENDER_call_portA_send,CMockString_cmock_arg3);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_cmock_arg3), (void*)(&cmock_arg3), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_ARINC_SENDER_call_portA_send,CMockString_cmock_arg4);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_cmock_arg4), (void*)(&cmock_arg4), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}
}

void CMockExpectParameters_ARINC_SENDER_call_portA_send(CMOCK_ARINC_SENDER_call_portA_send_CALL_INSTANCE* cmock_call_instance, ARINC_SENDER* cmock_arg1, char* cmock_arg2, size_t cmock_arg3, size_t cmock_arg4)
{
  cmock_call_instance->Expected_cmock_arg1 = cmock_arg1;
  cmock_call_instance->Expected_cmock_arg2 = cmock_arg2;
  memcpy(&cmock_call_instance->Expected_cmock_arg3, &cmock_arg3, sizeof(size_t));
  memcpy(&cmock_call_instance->Expected_cmock_arg4, &cmock_arg4, sizeof(size_t));
}

void ARINC_SENDER_call_portA_send_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ARINC_SENDER* cmock_arg1, char* cmock_arg2, size_t cmock_arg3, size_t cmock_arg4, ret_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ARINC_SENDER_call_portA_send_CALL_INSTANCE));
  CMOCK_ARINC_SENDER_call_portA_send_CALL_INSTANCE* cmock_call_instance = (CMOCK_ARINC_SENDER_call_portA_send_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ARINC_SENDER_call_portA_send_CallInstance = CMock_Guts_MemChain(Mock.ARINC_SENDER_call_portA_send_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_ARINC_SENDER_call_portA_send(cmock_call_instance, cmock_arg1, cmock_arg2, cmock_arg3, cmock_arg4);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(ret_t));
  UNITY_CLR_DETAILS();
}

ret_t ARINC_SENDER_call_portA_flush(ARINC_SENDER* cmock_arg1)
{
if (!ARINC_SENDER_call_portA_flush_UseMock)
{
  return _ARINC_SENDER_call_portA_flush_impl(cmock_arg1);
}
else
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_ARINC_SENDER_call_portA_flush_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_ARINC_SENDER_call_portA_flush);
  cmock_call_instance = (CMOCK_ARINC_SENDER_call_portA_flush_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.ARINC_SENDER_call_portA_flush_CallInstance);
  Mock.ARINC_SENDER_call_portA_flush_CallInstance = CMock_Guts_MemNext(Mock.ARINC_SENDER_call_portA_flush_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_ARINC_SENDER_call_portA_flush,CMockString_cmock_arg1);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_cmock_arg1), (void*)(cmock_arg1), sizeof(ARINC_SENDER), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}
}

void CMockExpectParameters_ARINC_SENDER_call_portA_flush(CMOCK_ARINC_SENDER_call_portA_flush_CALL_INSTANCE* cmock_call_instance, ARINC_SENDER* cmock_arg1)
{
  cmock_call_instance->Expected_cmock_arg1 = cmock_arg1;
}

void ARINC_SENDER_call_portA_flush_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ARINC_SENDER* cmock_arg1, ret_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ARINC_SENDER_call_portA_flush_CALL_INSTANCE));
  CMOCK_ARINC_SENDER_call_portA_flush_CALL_INSTANCE* cmock_call_instance = (CMOCK_ARINC_SENDER_call_portA_flush_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ARINC_SENDER_call_portA_flush_CallInstance = CMock_Guts_MemChain(Mock.ARINC_SENDER_call_portA_flush_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_ARINC_SENDER_call_portA_flush(cmock_call_instance, cmock_arg1);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(ret_t));
  UNITY_CLR_DETAILS();
}

