#******************************************************************
#
# Institute for System Programming of the Russian Academy of Sciences
# Copyright (C) 2016 ISPRAS
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, Version 3.
#
# This program is distributed in the hope # that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU General Public License version 3 for more details.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Import('syspart_env')

syspart_mocks_env = syspart_env.Clone()
syspart_mocks_env.Append(CPPPATH = syspart_mocks_env['JETOS_HOME']+'/syspart/components/arinc/')
syspart_mocks_env.Append(CPPPATH = syspart_mocks_env['JETOS_HOME']+'/syspart/components/arp/')
syspart_mocks_env.Append(CPPPATH = syspart_mocks_env['JETOS_HOME']+'/syspart/components/mac/')
syspart_mocks_env.Append(CPPPATH = syspart_mocks_env['JETOS_HOME']+'/syspart/components/ppc_dtsec/')
syspart_mocks_env.Append(CPPPATH = syspart_mocks_env['JETOS_HOME']+'/syspart/components/udp_ip/')
syspart_mocks_env.Append(CPPPATH = syspart_mocks_env['JETOS_HOME']+'/syspart/components/virtio/')
mocks = syspart_mocks_env.StaticObject(source = Glob('*.c'))

Return('mocks')

# EOF
