# -*- Mode: Python -*-

Import('libpok_env')

libpok_arinc_env = libpok_env.Clone()
libpok_arinc_env.Append(CPPPATH = libpok_arinc_env['POK_PATH']+'/libpok/arinc653')

libpok_env.Program(target = 'arinc653.lo', source = Glob('*.c'))

# EOF
