#******************************************************************
#
# Institute for System Programming of the Russian Academy of Sciences
# Copyright (C) 2016 ISPRAS
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, Version 3.
#
# This program is distributed in the hope # that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU General Public License version 3 for more details.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

"""
Environment definitions for e500v2 board based on PowerPC.
"""

Import('env')

env['ARCH'] = 'ppc'

SConscript(env['JETOS_HOME'] + '/misc/arch/ppc/SConscript', exports = 'env')

env['PREFIX'] = 'powerpc-elf-eabispe-' # This will rewrite PREFIX set by arch

env.Append(CFLAGS = ' -mcpu=8548 -mspe=yes -mfloat-gprs=double -mno-eabi')
env.Append(ASFLAGS = ' -mcpu=8548 -mspe=yes -mfloat-gprs=double -mno-eabi')

env['BOARD_IS_EMULATED'] = True
env.Append(QEMU_FLAGS = ' -M ppce500 -cpu e500v2')
