#******************************************************************
#
# Institute for System Programming of the Russian Academy of Sciences
# Copyright (C) 2016 ISPRAS
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, Version 3.
#
# This program is distributed in the hope # that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU General Public License version 3 for more details.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

"""
Environment definitions for 'QEMU sabrelite machine -
Freescale i.MX6 Quad SABRE Lite Board (Cortex A9) board
"""

Import('env')

env['ARCH'] = 'arm'

SConscript(env['JETOS_HOME'] + '/misc/arch/arm/SConscript', exports = 'env')

env.Append(CFLAGS = ' -mcpu=cortex-a9')
env.Append(ASFLAGS = ' -mcpu=cortex-a9')

env['BOARD_IS_EMULATED'] = True
env.Append(QEMU_FLAGS = ' -M sabrelite')
