#******************************************************************
#
# Institute for System Programming of the Russian Academy of Sciences
# Copyright (C) 2016 ISPRAS
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, Version 3.
#
# This program is distributed in the hope # that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU General Public License version 3 for more details.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Import('syspart_env')

p3041_env = syspart_env.Clone()

p3041_env.Append(CPPPATH = syspart_env['POK_PATH']+'/syspart/drivers/p3041/include')

#syspart_env.Program(target = 'p3041.lo', source = Glob('fm/*.c'))
p3041 = p3041_env.StaticObject(source = ['init.c'])

Return('p3041')

#Export('syspart_env')
#
#SConscript('net/SConscript')
#SConscript('drivers/SConscript')

# EOF
