#******************************************************************
#
# Institute for System Programming of the Russian Academy of Sciences
# Copyright (C) 2016 ISPRAS
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, Version 3.
#
# This program is distributed in the hope # that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU General Public License version 3 for more details.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Import('env')

libpok_env = env.Clone()

libpok_env['CPPPATH'] = [env['POK_PATH']+'/libpok/include']

libpok_env.StaticLibrary(target = 'pok', source = [
'arch/arch.lo',
'core/core.lo',
'middleware/middleware.lo',
'arinc653/arinc653.lo',
'libm/libm.lo',
'protocols/protocols.lo',
'utils/utils.lo',
'libc/libc.lo'])

Export('libpok_env')

SConscript('arch/SConscript')
SConscript('core/SConscript')
SConscript('middleware/SConscript')
SConscript('arinc653/SConscript')
SConscript('libm/SConscript')
SConscript('protocols/SConscript')
SConscript('libc/SConscript')
SConscript('utils/SConscript')

# EOF
