# -*- Mode: Python -*-

Import('env')

pr1_env = env.Clone()
pr1_env['CPPPATH'] = pr1_env['POK_PATH']+'/libpok/include'
pr1_env.Append(CFLAGS = ' -include '+pr1_env['POK_PATH']+'/libpok/include/config.h')

build_path_libpok = pr1_env['POK_PATH']+'/build/'+pr1_env['BSP']+'/libpok'

ldscript = pr1_env['POK_PATH']+'/boards/'+pr1_env['BSP']+'/ldscripts/partition.lds'
pr1_env['LINKFLAGS'] = str(' -T '+ldscript+' -Map pr1/pr1.elf.map')

objs = pr1_env.StaticObject(source = Glob('*.c'))

source_objs = ''
for obj in objs:
    source_objs += 'pr1/' + str(obj) + ' '

pr1_command = pr1_env.Command(target = 'pr1.elf',
source = [],
action = pr1_env['LINK']+pr1_env['LINKFLAGS']+' '+
source_objs +
' -o pr1/pr1.elf -L'+build_path_libpok+' -lpok '+
pr1_env['LIBGCC'])
pr1_env.Depends(pr1_command, [objs, build_path_libpok+'/libpok.a', ldscript])

# EOF
