#******************************************************************
#
# Institute for System Programming of the Russian Academy of Sciences
# Copyright (C) 2016 ISPRAS
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, Version 3.
#
# This program is distributed in the hope # that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU General Public License version 3 for more details.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Import('syspart_env')

syspart_env['CPPPATH'].append([syspart_env['JETOS_HOME']+'/syspart/include'])

Export('syspart_env')

syspart_objects = []

syspart_objects += SConscript('drivers/SConscript')
syspart_objects += SConscript('components/SConscript')

if syspart_env.get('libpoktests'):
    syspart_env['CPPPATH'].append([
        syspart_env['JETOS_UNITTESTS']+'/mocks/syspart/',
        syspart_env['JETOS_UNITTESTS']+'/unity/'
    ])
    syspart_objects += SConscript(syspart_env['JETOS_UNITTESTS'] + '/mocks/SConscript',
        variant_dir = 'mocks',
        duplicate = 0
    )

syspart_program = syspart_env.StaticLibrary(target = 'syspart', source = [
    syspart_objects,
    'pool.c'
])

Return('syspart_program')

# EOF
