#******************************************************************
#
# Institute for System Programming of the Russian Academy of Sciences
# Copyright (C) 2016 ISPRAS
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, Version 3.
#
# This program is distributed in the hope # that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU General Public License version 3 for more details.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Import('env')

syspart_env = env.Clone()

syspart_env['CPPPATH'] = [env['POK_PATH']+'/build/libpok/include',
                          env['POK_PATH']+'/libpok/include',
                          env['POK_PATH']+'/syspart/include',
                          ]

syspart_program = syspart_env.Program(target = 'syspart.lo', source = [
    'net/net.lo',
    'drivers/drivers.lo',
    'config.c',
    'mem.c'
])
syspart_env.Depends(syspart_program, env['POK_PATH']+'/libpok/')

Export('syspart_env')

SConscript('net/SConscript')
SConscript('drivers/SConscript')

# EOF
