#******************************************************************
#
# Institute for System Programming of the Russian Academy of Sciences
# Copyright (C) 2016 ISPRAS
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, Version 3.
#
# This program is distributed in the hope # that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU General Public License version 3 for more details.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Import('env')

syspart_env = env.PartitionEnvironment()

syspart_env['CPPPATH'].append([env['POK_PATH']+'/syspart/include'])

Export('syspart_env')

drivers = SConscript('drivers/SConscript')
components = SConscript('components/SConscript')

syspart_program = syspart_env.Program(target = 'syspart.lo', source = [
    drivers,
    components,
    'pool.c'
])

Return('syspart_program')

# EOF
