# -*- Mode: Python -*-

Import('libpok_env')

libpok_blowfish_env = libpok_env.Clone()
libpok_blowfish_env.Append(CPPPATH = libpok_blowfish_env['POK_PATH']+'/libpok/protocols/blowfish')

libpok_blowfish_env.Program(target = 'blowfish.lo', source = Glob('*.c'))

# EOF
