# -*- Mode: Python -*-

Import('env')

env.Program(target = 'core.lo', source = [
'partition.c',
'debug.c',
'kernel.c',
'lockobj.c',
'thread.c',
'instrumentation.c',
'sched.c',
'sched_fps.c',
'time.c',
'syscall.c',
'error.c',
'loader.c',
'boot.c',
'cons.c'])

# EOF
