#******************************************************************
#
# Institute for System Programming of the Russian Academy of Sciences
# Copyright (C) 2016 ISPRAS
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, Version 3.
#
# This program is distributed in the hope # that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU General Public License version 3 for more details.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Import('part_env')
Import('part_build_dir')

P2_env = part_env.Clone()
P2_env.Append(CFLAGS = ' -O3')

#VariantDir(part_build_dir, '.', duplicate = 0)
#objs = P2_env.StaticObject(source = Glob(part_build_dir+'*.c'))

objs = []
sources = Glob('*.c')
for src in sources:
    objs += P2_env.StaticObject(part_build_dir + str(src)[:-2], src)

Return('objs')
