# -*- Mode: Python -*-

Import('libpok_env')

import sys
import os
sys.path.insert(1, os.path.join(os.environ["POK_PATH"], "misc"))
import generate_syscalls

libpok_env.Append(CPPPATH = libpok_env['POK_PATH']+'/build/libpok/include')

generate_syscall_user_command = libpok_env.Command(
    target = libpok_env['POK_PATH'] + 'build/libpok/include/pok/syscall_map_arinc.h',
    source = libpok_env["POK_PATH"] + 'kernel/include/uapi/syscall_map_arinc.h.in',
    action = generate_syscalls.generate_syscalls_declaration_user)

libpok_program = libpok_env.Program(target = 'core.lo', source = Glob('*.c'))
libpok_env.Depends(libpok_program, generate_syscall_user_command)

# EOF
