# -*- Mode: Python -*-

Import('env')

kernel_env = env.Clone()
kernel_env.Append(CFLAGS = ' -include '+kernel_env['POK_PATH']+'/kernel/include/config.h -Werror')

kernel_env.Program(target = 'pok.lo', source = [
'core/core.lo',
'middleware/middleware.lo',
'libc/libc.lo',
'arch/arch.lo',
'drivers/drivers.lo',
'net/net.lo'])

Export('kernel_env')

#kernel_env.SConsignFile(kernel_env['POK_PATH']+'/kernel/scons_signatures')
#SConsignFile(None)

SConscript('core/SConscript')
SConscript('middleware/SConscript')
SConscript('libc/SConscript')
SConscript('arch/SConscript')
SConscript('drivers/SConscript')
SConscript('net/SConscript')

# EOF
