# -*- Mode: Python -*-

Import('env')

env.Program(target = 'middleware.lo', source = [
'portsampling_ops.c',
'portqueueing_utils.c',
'portqueueing_ops.c',
'portflushall.c',
'portinit.c',
'portreset.c'])

# EOF
