#******************************************************************
#
# Institute for System Programming of the Russian Academy of Sciences
# Copyright (C) 2016 ISPRAS
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, Version 3.
#
# This program is distributed in the hope # that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU General Public License version 3 for more details.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

import os

Import('syspart_env')

COMPONENTS_LIST = ['X', 'Y']

comp_env = syspart_env.Clone()
comp_objs = []
#comp_gens = []

for comp in COMPONENTS_LIST:
    objs = SConscript(os.path.join(comp, 'SConscript'),
                          #variant_dir='build/%s' % comp,
                          #duplicate=0,
                          exports=['comp_env'])
    comp_objs.append(objs)
    #comp_gens.append(gens)
Return('comp_objs')

#if syspart_env.get('jdeveloper'):
#    import sys
#    sys.path.insert(1, os.path.join(os.environ["POK_PATH"], "misc"))
#    import template_generation
