# -*- Mode: Python -*-

import os

cflags = ''
SConscript(os.environ['POK_PATH']+'/misc/SConscript', exports = 'cflags')

Import('env')
SConscript(env['POK_PATH']+'/misc/SConscript_partition_base')

env.Clean('chpok', env['POK_PATH']+'/build/')
env.Clean('local', 'build')

# EOF
