# -*- Mode: Python -*-

import os

SConscript(os.environ['POK_PATH']+'/misc/SConscript')

Import('env')
SConscript(env['POK_PATH']+'/misc/SConscript_base')

env.Clean('chpok', env['POK_PATH']+'/build/')
env.Clean('local', ['build/', [pdir+'/build' for pdir in env['PARTITION_DIRS']]])

# EOF
