#******************************************************************
#
# Institute for System Programming of the Russian Academy of Sciences
# Copyright (C) 2016 ISPRAS
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, Version 3.
#
# This program is distributed in the hope # that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU General Public License version 3 for more details.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

"""
Environment definitions for MIPS1 board based on MIPS arch.
"""

Import('env')

env['ARCH'] = 'mips'

SConscript(env['JETOS_HOME'] + '/misc/arch/mips/SConscript', exports = 'env')

env.Append(CFLAGS = ' -mips32')

env['BOARD_PHYS_SIZE'] = 2**28 # 256M

env['BOARD_IS_EMULATED'] = True
env.Append(QEMU_FLAGS = ' -machine duna')
