/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKARINC_SENDER_GEN_H
#define _MOCKARINC_SENDER_GEN_H

#include <ARINC_SENDER_gen.h>

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void MockARINC_SENDER_gen_Init(void);
void MockARINC_SENDER_gen_Destroy(void);
void MockARINC_SENDER_gen_Verify(void);




#define ARINC_SENDER_call_portA_send_ExpectAndReturn(cmock_arg1, cmock_arg2, cmock_arg3, cmock_arg4, cmock_retval) ARINC_SENDER_call_portA_send_CMockExpectAndReturn(__LINE__, cmock_arg1, cmock_arg2, cmock_arg3, cmock_arg4, cmock_retval)
void ARINC_SENDER_call_portA_send_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ARINC_SENDER* cmock_arg1, char* cmock_arg2, size_t cmock_arg3, size_t cmock_arg4, ret_t cmock_to_return);
int ARINC_SENDER_call_portA_send_UseMock;
ret_t _ARINC_SENDER_call_portA_send_impl(ARINC_SENDER* cmock_arg1, char* cmock_arg2, size_t cmock_arg3, size_t cmock_arg4);

#define ARINC_SENDER_call_portA_flush_ExpectAndReturn(cmock_arg1, cmock_retval) ARINC_SENDER_call_portA_flush_CMockExpectAndReturn(__LINE__, cmock_arg1, cmock_retval)
void ARINC_SENDER_call_portA_flush_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ARINC_SENDER* cmock_arg1, ret_t cmock_to_return);
int ARINC_SENDER_call_portA_flush_UseMock;
ret_t _ARINC_SENDER_call_portA_flush_impl(ARINC_SENDER* cmock_arg1);


#endif
