# -*- Mode: Python -*-

Import('libpok_env')

libpok_arch_env = libpok_env.Clone()
libpok_arch_env.Append(CPPPATH = libpok_arch_env['POK_PATH']+'/libpok/arch/'+libpok_arch_env['ARCH'])

libpok_arch_env.Program(target = 'arch.lo', source = libpok_arch_env['ARCH']+'/'+libpok_arch_env['ARCH']+'.lo')

Export('libpok_arch_env')

SConscript('./'+libpok_arch_env['ARCH']+'/SConscript')

# EOF
