# -*- Mode: Python -*-

Import('libpok_env')

libpok_string_env = libpok_env.Clone()
libpok_string_env.Append(CPPPATH = libpok_string_env['POK_PATH']+'/libpok/libc/string')

libpok_env.Program(target = 'string.lo', source = Glob('*.c'))

# EOF
