# -*- Mode: Python -*-

Import('kernel_env')

kernel_env.Program(target = 'e500mc.lo', source = Glob('*.c'))

kernel_env.Depends('ppc.lo', [kernel_env['BSP']+'/'+kernel_env['BSP']+'.lo', 'libfdt/libfdt.lo'])

# EOF
