# -*- Mode: Python -*-

Import('syspart_env')

syspart_env.Program(target = 'drivers.lo', source = [
    'virtio/virtio.lo',
    'ne2000/ne2000.lo',
    'p3041/p3041.lo',
    'pci/pci.lo'
])


SConscript('virtio/SConscript')
SConscript('ne2000/SConscript')
SConscript('pci/SConscript')
SConscript('p3041/SConscript')

# EOF
