/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKARINC_PROCESS_QUEUE_H
#define _MOCKARINC_PROCESS_QUEUE_H

#include "arinc_process_queue.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockarinc_process_queue_Init(void);
void Mockarinc_process_queue_Destroy(void);
void Mockarinc_process_queue_Verify(void);




#define arinc_process_queue_add_Expect(wq) arinc_process_queue_add_CMockExpect(__LINE__, wq)
void arinc_process_queue_add_CMockExpect(UNITY_LINE_TYPE cmock_line, struct msection_wq* wq);
#define arinc_process_queue_add_common_Expect(wq, discipline) arinc_process_queue_add_common_CMockExpect(__LINE__, wq, discipline)
void arinc_process_queue_add_common_CMockExpect(UNITY_LINE_TYPE cmock_line, struct msection_wq* wq, QUEUING_DISCIPLINE_TYPE discipline);

#endif
