/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKARINC_ALLOC_H
#define _MOCKARINC_ALLOC_H

#include <arinc_alloc.h>

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockarinc_alloc_Init(void);
void Mockarinc_alloc_Destroy(void);
void Mockarinc_alloc_Verify(void);




#define arinc_allocator_init_Expect() arinc_allocator_init_CMockExpect(__LINE__)
void arinc_allocator_init_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define arinc_alloc_ExpectAndReturn(size, alignment, cmock_retval) arinc_alloc_CMockExpectAndReturn(__LINE__, size, alignment, cmock_retval)
void arinc_alloc_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, size_t size, size_t alignment, void* cmock_to_return);
#define arinc_allocator_get_state_ExpectAndReturn(cmock_retval) arinc_allocator_get_state_CMockExpectAndReturn(__LINE__, cmock_retval)
void arinc_allocator_get_state_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, arinc_allocator_state cmock_to_return);
#define arinc_allocator_reset_state_Expect(state) arinc_allocator_reset_state_CMockExpect(__LINE__, state)
void arinc_allocator_reset_state_CMockExpect(UNITY_LINE_TYPE cmock_line, arinc_allocator_state state);

#endif
