/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKMSECTION_H
#define _MOCKMSECTION_H

#include <msection_defs.h>

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockmsection_Init(void);
void Mockmsection_Destroy(void);
void Mockmsection_Verify(void);




#define msection_init_Expect(section) msection_init_CMockExpect(__LINE__, section)
void msection_init_CMockExpect(UNITY_LINE_TYPE cmock_line, struct msection* section);
#define msection_enter_Expect(section) msection_enter_CMockExpect(__LINE__, section)
void msection_enter_CMockExpect(UNITY_LINE_TYPE cmock_line, struct msection* section);
#define msection_leave_Expect(section) msection_leave_CMockExpect(__LINE__, section)
void msection_leave_CMockExpect(UNITY_LINE_TYPE cmock_line, struct msection* section);
#define msection_wait_ExpectAndReturn(section, timeout, cmock_retval) msection_wait_CMockExpectAndReturn(__LINE__, section, timeout, cmock_retval)
void msection_wait_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct msection* section, pok_time_t timeout, pok_ret_t cmock_to_return);
#define msection_notify_ExpectAndReturn(section, thread_id, cmock_retval) msection_notify_CMockExpectAndReturn(__LINE__, section, thread_id, cmock_retval)
void msection_notify_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct msection* section, pok_thread_id_t thread_id, pok_ret_t cmock_to_return);
#define msection_wq_init_Expect(wq) msection_wq_init_CMockExpect(__LINE__, wq)
void msection_wq_init_CMockExpect(UNITY_LINE_TYPE cmock_line, struct msection_wq* wq);
#define msection_wq_add_Expect(wq, next) msection_wq_add_CMockExpect(__LINE__, wq, next)
void msection_wq_add_CMockExpect(UNITY_LINE_TYPE cmock_line, struct msection_wq* wq, pok_thread_id_t next);
#define msection_wq_add_after_Expect(wq, prev) msection_wq_add_after_CMockExpect(__LINE__, wq, prev)
void msection_wq_add_after_CMockExpect(UNITY_LINE_TYPE cmock_line, struct msection_wq* wq, pok_thread_id_t prev);
#define msection_wq_del_Expect(wq, thread) msection_wq_del_CMockExpect(__LINE__, wq, thread)
void msection_wq_del_CMockExpect(UNITY_LINE_TYPE cmock_line, struct msection_wq* wq, pok_thread_id_t thread);
#define msection_wq_notify_ExpectAndReturn(section, wq, is_all, cmock_retval) msection_wq_notify_CMockExpectAndReturn(__LINE__, section, wq, is_all, cmock_retval)
void msection_wq_notify_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct msection* section, struct msection_wq* wq, pok_bool_t is_all, pok_ret_t cmock_to_return);
#define msection_wq_size_ExpectAndReturn(section, wq, cmock_retval) msection_wq_size_CMockExpectAndReturn(__LINE__, section, wq, cmock_retval)
void msection_wq_size_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct msection* section, struct msection_wq* wq, size_t cmock_to_return);

#endif
