# -*- Mode: Python -*-

Import('env')
Import('part_build_dir')

part_env = env.Clone()
part_env['CPPPATH'] = part_env['POK_PATH']+'libpok/include'
part_env.Append(CFLAGS = ' -include '+part_env['POK_PATH']+'libpok/include/config.h')

ldscript = part_env['POK_PATH']+'boards/'+part_env['BSP']+'/ldscripts/partition.lds'
part_env['LINKFLAGS'] = str(' -T '+ldscript+' -Map '+part_build_dir+'part.elf.map')

libpok = part_env['POK_PATH']+'build/'+part_env['BSP']+'/libpok/libpok.a'

part_elf = part_env.Program(target = 'part.elf', source = [
Glob('*.c'),
libpok,
part_env['LIBGCC']],
srcdir = part_build_dir)
part_env.Depends(part_elf, ldscript)

# EOF
