# -*- Mode: Python -*-

Import('libpok_env')

libpok_env.Program(target = 'libc.lo', source = [
'stdio/stdio.lo',
'string/string.lo',
'stdlib/stdlib.lo'])

SConscript('./stdio/SConscript')
SConscript('./string/SConscript')
SConscript('./stdlib/SConscript')

# EOF
