/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <unity/unity.h>
#include <unity/cmock.h>
#include <mocks/Mockarinc_alloc.h>

static const char* CMockString_alignment = "alignment";
static const char* CMockString_arinc_alloc = "arinc_alloc";
static const char* CMockString_arinc_allocator_get_state = "arinc_allocator_get_state";
static const char* CMockString_arinc_allocator_init = "arinc_allocator_init";
static const char* CMockString_arinc_allocator_reset_state = "arinc_allocator_reset_state";
static const char* CMockString_size = "size";
static const char* CMockString_state = "state";

typedef struct _CMOCK_arinc_allocator_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_arinc_allocator_init_CALL_INSTANCE;

typedef struct _CMOCK_arinc_alloc_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  void* ReturnVal;
  size_t Expected_size;
  size_t Expected_alignment;

} CMOCK_arinc_alloc_CALL_INSTANCE;

typedef struct _CMOCK_arinc_allocator_get_state_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  arinc_allocator_state ReturnVal;

} CMOCK_arinc_allocator_get_state_CALL_INSTANCE;

typedef struct _CMOCK_arinc_allocator_reset_state_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  arinc_allocator_state Expected_state;

} CMOCK_arinc_allocator_reset_state_CALL_INSTANCE;

static struct Mockarinc_allocInstance
{
  CMOCK_MEM_INDEX_TYPE arinc_allocator_init_CallInstance;
  CMOCK_MEM_INDEX_TYPE arinc_alloc_CallInstance;
  CMOCK_MEM_INDEX_TYPE arinc_allocator_get_state_CallInstance;
  CMOCK_MEM_INDEX_TYPE arinc_allocator_reset_state_CallInstance;
} Mock;


void Mockarinc_alloc_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_arinc_allocator_init);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.arinc_allocator_init_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_arinc_alloc);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.arinc_alloc_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_arinc_allocator_get_state);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.arinc_allocator_get_state_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_arinc_allocator_reset_state);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.arinc_allocator_reset_state_CallInstance, cmock_line, CMockStringCalledLess);
}

void Mockarinc_alloc_Init(void)
{
  Mockarinc_alloc_Destroy();
}

void Mockarinc_alloc_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void arinc_allocator_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_arinc_allocator_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_arinc_allocator_init);
  cmock_call_instance = (CMOCK_arinc_allocator_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.arinc_allocator_init_CallInstance);
  Mock.arinc_allocator_init_CallInstance = CMock_Guts_MemNext(Mock.arinc_allocator_init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void arinc_allocator_init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_arinc_allocator_init_CALL_INSTANCE));
  CMOCK_arinc_allocator_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_arinc_allocator_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.arinc_allocator_init_CallInstance = CMock_Guts_MemChain(Mock.arinc_allocator_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

void* arinc_alloc(size_t size, size_t alignment)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_arinc_alloc_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_arinc_alloc);
  cmock_call_instance = (CMOCK_arinc_alloc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.arinc_alloc_CallInstance);
  Mock.arinc_alloc_CallInstance = CMock_Guts_MemNext(Mock.arinc_alloc_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_arinc_alloc,CMockString_size);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_size), (void*)(&size), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_arinc_alloc,CMockString_alignment);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_alignment), (void*)(&alignment), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_arinc_alloc(CMOCK_arinc_alloc_CALL_INSTANCE* cmock_call_instance, size_t size, size_t alignment)
{
  memcpy(&cmock_call_instance->Expected_size, &size, sizeof(size_t));
  memcpy(&cmock_call_instance->Expected_alignment, &alignment, sizeof(size_t));
}

void arinc_alloc_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, size_t size, size_t alignment, void* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_arinc_alloc_CALL_INSTANCE));
  CMOCK_arinc_alloc_CALL_INSTANCE* cmock_call_instance = (CMOCK_arinc_alloc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.arinc_alloc_CallInstance = CMock_Guts_MemChain(Mock.arinc_alloc_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_arinc_alloc(cmock_call_instance, size, alignment);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

arinc_allocator_state arinc_allocator_get_state(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_arinc_allocator_get_state_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_arinc_allocator_get_state);
  cmock_call_instance = (CMOCK_arinc_allocator_get_state_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.arinc_allocator_get_state_CallInstance);
  Mock.arinc_allocator_get_state_CallInstance = CMock_Guts_MemNext(Mock.arinc_allocator_get_state_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void arinc_allocator_get_state_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, arinc_allocator_state cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_arinc_allocator_get_state_CALL_INSTANCE));
  CMOCK_arinc_allocator_get_state_CALL_INSTANCE* cmock_call_instance = (CMOCK_arinc_allocator_get_state_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.arinc_allocator_get_state_CallInstance = CMock_Guts_MemChain(Mock.arinc_allocator_get_state_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(arinc_allocator_state));
  UNITY_CLR_DETAILS();
}

void arinc_allocator_reset_state(arinc_allocator_state state)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_arinc_allocator_reset_state_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_arinc_allocator_reset_state);
  cmock_call_instance = (CMOCK_arinc_allocator_reset_state_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.arinc_allocator_reset_state_CallInstance);
  Mock.arinc_allocator_reset_state_CallInstance = CMock_Guts_MemNext(Mock.arinc_allocator_reset_state_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_arinc_allocator_reset_state,CMockString_state);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_state), (void*)(&state), sizeof(arinc_allocator_state), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_arinc_allocator_reset_state(CMOCK_arinc_allocator_reset_state_CALL_INSTANCE* cmock_call_instance, arinc_allocator_state state)
{
  memcpy(&cmock_call_instance->Expected_state, &state, sizeof(arinc_allocator_state));
}

void arinc_allocator_reset_state_CMockExpect(UNITY_LINE_TYPE cmock_line, arinc_allocator_state state)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_arinc_allocator_reset_state_CALL_INSTANCE));
  CMOCK_arinc_allocator_reset_state_CALL_INSTANCE* cmock_call_instance = (CMOCK_arinc_allocator_reset_state_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.arinc_allocator_reset_state_CallInstance = CMock_Guts_MemChain(Mock.arinc_allocator_reset_state_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_arinc_allocator_reset_state(cmock_call_instance, state);
  UNITY_CLR_DETAILS();
}

