/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <unity/unity.h>
#include <unity/cmock.h>
#include <mocks/Mockarinc_process_queue.h>

static const char* CMockString_arinc_process_queue_add = "arinc_process_queue_add";
static const char* CMockString_arinc_process_queue_add_common = "arinc_process_queue_add_common";
static const char* CMockString_discipline = "discipline";
static const char* CMockString_wq = "wq";

typedef struct _CMOCK_arinc_process_queue_add_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  struct msection_wq* Expected_wq;

} CMOCK_arinc_process_queue_add_CALL_INSTANCE;

typedef struct _CMOCK_arinc_process_queue_add_common_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  struct msection_wq* Expected_wq;
  QUEUING_DISCIPLINE_TYPE Expected_discipline;

} CMOCK_arinc_process_queue_add_common_CALL_INSTANCE;

static struct Mockarinc_process_queueInstance
{
  CMOCK_MEM_INDEX_TYPE arinc_process_queue_add_CallInstance;
  CMOCK_MEM_INDEX_TYPE arinc_process_queue_add_common_CallInstance;
} Mock;

void Mockarinc_process_queue_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_arinc_process_queue_add);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.arinc_process_queue_add_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_arinc_process_queue_add_common);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.arinc_process_queue_add_common_CallInstance, cmock_line, CMockStringCalledLess);
}

void Mockarinc_process_queue_Init(void)
{
  Mockarinc_process_queue_Destroy();
}

void Mockarinc_process_queue_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void arinc_process_queue_add(struct msection_wq* wq)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_arinc_process_queue_add_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_arinc_process_queue_add);
  cmock_call_instance = (CMOCK_arinc_process_queue_add_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.arinc_process_queue_add_CallInstance);
  Mock.arinc_process_queue_add_CallInstance = CMock_Guts_MemNext(Mock.arinc_process_queue_add_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_arinc_process_queue_add,CMockString_wq);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_wq), (void*)(wq), sizeof(struct msection_wq), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_arinc_process_queue_add(CMOCK_arinc_process_queue_add_CALL_INSTANCE* cmock_call_instance, struct msection_wq* wq)
{
  cmock_call_instance->Expected_wq = wq;
}

void arinc_process_queue_add_CMockExpect(UNITY_LINE_TYPE cmock_line, struct msection_wq* wq)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_arinc_process_queue_add_CALL_INSTANCE));
  CMOCK_arinc_process_queue_add_CALL_INSTANCE* cmock_call_instance = (CMOCK_arinc_process_queue_add_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.arinc_process_queue_add_CallInstance = CMock_Guts_MemChain(Mock.arinc_process_queue_add_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_arinc_process_queue_add(cmock_call_instance, wq);
  UNITY_CLR_DETAILS();
}

void arinc_process_queue_add_common(struct msection_wq* wq, QUEUING_DISCIPLINE_TYPE discipline)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_arinc_process_queue_add_common_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_arinc_process_queue_add_common);
  cmock_call_instance = (CMOCK_arinc_process_queue_add_common_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.arinc_process_queue_add_common_CallInstance);
  Mock.arinc_process_queue_add_common_CallInstance = CMock_Guts_MemNext(Mock.arinc_process_queue_add_common_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_arinc_process_queue_add_common,CMockString_wq);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_wq), (void*)(wq), sizeof(struct msection_wq), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_arinc_process_queue_add_common,CMockString_discipline);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_discipline), (void*)(&discipline), sizeof(QUEUING_DISCIPLINE_TYPE), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_arinc_process_queue_add_common(CMOCK_arinc_process_queue_add_common_CALL_INSTANCE* cmock_call_instance, struct msection_wq* wq, QUEUING_DISCIPLINE_TYPE discipline)
{
  cmock_call_instance->Expected_wq = wq;
  memcpy(&cmock_call_instance->Expected_discipline, &discipline, sizeof(QUEUING_DISCIPLINE_TYPE));
}

void arinc_process_queue_add_common_CMockExpect(UNITY_LINE_TYPE cmock_line, struct msection_wq* wq, QUEUING_DISCIPLINE_TYPE discipline)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_arinc_process_queue_add_common_CALL_INSTANCE));
  CMOCK_arinc_process_queue_add_common_CALL_INSTANCE* cmock_call_instance = (CMOCK_arinc_process_queue_add_common_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.arinc_process_queue_add_common_CallInstance = CMock_Guts_MemChain(Mock.arinc_process_queue_add_common_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_arinc_process_queue_add_common(cmock_call_instance, wq, discipline);
  UNITY_CLR_DETAILS();
}

